name: Deploy To Server

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 部署到测试环境服务器
      - name: Deploy To Test Environment
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/projects/ollah/server
            git pull
            pnpm i
            pnpm build
            pm2 start
