name: Deploy To Server

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 部署到预发环境
      - name: Deploy To Pre
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: '${{ secrets.PRE_SERVER_HOST }}'
          username: ${{ secrets.PRE_SERVER_NAME }}
          key: ${{ secrets.PRE_SERVER_SSH_KEY }}
          script: |
            whoami
            cd ~/projects/ollah/ollah-server
            pnpm i
            pnpm build
            pm2 start
